# Generated by Django 2.1.7 on 2019-02-21 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('latitude', models.FloatField(db_column='latitude')),
                ('longitude', models.FloatField(db_column='longitude')),
                ('address', models.FloatField(db_column='address')),
                ('source', models.TextField(db_column='source')),
                ('metadata', models.TextField(db_column='metadata')),
                ('created_at', models.DateTimeField(db_column='created_at', default=datetime.datetime(2019, 2, 21, 3, 39, 42, 850567, tzinfo=utc))),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=datetime.datetime(2019, 2, 21, 3, 39, 42, 850601, tzinfo=utc))),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False)),
            ],
        ),
    ]
