# Generated by Django 2.1.7 on 2019-02-21 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('StoreTinder', '0004_auto_20190221_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', default=datetime.datetime(2019, 2, 21, 3, 39, 56, 375786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stores',
            name='updated_at',
            field=models.DateTimeField(db_column='updated_at', default=datetime.datetime(2019, 2, 21, 3, 39, 56, 375820, tzinfo=utc)),
        ),
    ]
