# Generated by Django 2.1.7 on 2019-02-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreTinder', '0005_auto_20190221_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='created_at',
            field=models.DateTimeField(db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='updated_at',
            field=models.DateTimeField(db_column='updated_at'),
        ),
    ]
