# Generated by Django 2.1.7 on 2019-02-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreTinder', '0009_auto_20190226_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='address',
            field=models.TextField(db_column='address'),
        ),
    ]
