# Generated by Django 2.1.7 on 2019-02-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreTinder', '0010_auto_20190227_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
