# Generated by Django 2.1.7 on 2019-02-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('storeid', models.IntegerField(db_column='storeID', primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('storename', models.TextField(blank=True, db_column='storeName', null=True)),
                ('storeaddress', models.TextField(blank=True, db_column='storeAddress', null=True)),
                ('storephone', models.TextField(blank=True, db_column='storePhone', null=True)),
                ('weekdayopen', models.TextField(blank=True, db_column='weekDayOpen', null=True)),
                ('weekdayclose', models.TextField(blank=True, db_column='weekDayClose', null=True)),
                ('weekendopen', models.TextField(blank=True, db_column='weekEndOpen', null=True)),
                ('weekendclose', models.TextField(blank=True, db_column='weekEndClose', null=True)),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
    ]
