# Generated by Django 2.1.7 on 2019-02-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kfcstores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stores',
            options={'managed': True},
        ),
    ]
