# Generated by Django 2.1.7 on 2019-02-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kfcstores', '0003_auto_20190214_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='storephone',
            field=models.TextField(db_column='storePhone', default='-'),
        ),
    ]
