version: '3'

services:
  kfcsite:
    image: kfcsite:v3
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    image: kfcsite:v3
    command: >
      bash -c "python3 manage.py makemigrations && 
               python3 manage.py migrate"